# Generated by Django 2.2 on 2020-11-27 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Vine', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vine',
            name='vine_poster',
        ),
    ]
