# Generated by Django 2.2 on 2020-11-27 18:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Vine', '0002_remove_vine_vine_poster'),
    ]

    operations = [
        migrations.AddField(
            model_name='vine',
            name='vine_poster',
            field=models.FileField(default=django.utils.timezone.now, upload_to=''),
            preserve_default=False,
        ),
    ]
