# Generated by Django 2.2.9 on 2020-01-30 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Vine', '0003_auto_20200127_0424'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vine',
            name='dislikes',
        ),
        migrations.RemoveField(
            model_name='vine',
            name='isDisLiked',
        ),
        migrations.RemoveField(
            model_name='vine',
            name='isLiked',
        ),
        migrations.RemoveField(
            model_name='vine',
            name='likes',
        ),
    ]
