# Generated by Django 2.2.9 on 2020-01-31 17:09

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('Vine', '0005_auto_20200201_0202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vine',
            name='dislikes',
            field=django_mysql.models.ListCharField(models.CharField(max_length=100), default=[], max_length=66, size=None),
        ),
        migrations.AlterField(
            model_name='vine',
            name='likes',
            field=django_mysql.models.ListCharField(models.CharField(max_length=100), default=[], max_length=66, size=None),
        ),
    ]
